default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: app_server_development

test:
  <<: *default
  database: app_server_test

production:
  <<: *default
  database: app_server_production
  username: app_server
  password: <%= ENV['APP_SERVER_DATABASE_PASSWORD'] %>
