default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: app_server_development

test:
  <<: *default
  database: app_server_test

production:
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_DATABASE'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  adapter: mysql2
  encoding: utf8
  reconnect: true

