source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'mysql2', '>= 0.3.13', '< 0.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'haml', '~> 4.0.7'
gem 'jquery-rails', '~> 4.1.1'
gem 'underscore-rails', '~> 1.8.3'
gem 'angularjs-rails', '~> 1.5.0'
gem 'angular-rails-templates', '~> 1.0.0'
gem 'angularjs-rails-resource', '~> 2.0.0'
gem 'rest-client', '~> 1.6.7'

gem 'turbolinks', '~> 2.5.3'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug', '~> 9.0.4'
  gem 'rspec-rails', '~> 3.4.2'
  gem 'jasmine', '~> 2.3.1'
end

group :test do
  gem 'webmock', '~> 1.22.6'
  gem 'thin', '~> 1.6.4'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring', '~> 1.7.1'
end

